[package]
name = "jelatofish"
version = "0.1.0"
authors = ["Amane Katagiri <amane@ama.ne.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libm = "0.1.4"
image = "0.23.14"
