[tasks.html]
description = "wasmを実行するhtmlファイル群を生成する"
script = [
'''
#!/bin/bash
mkdir -p ./build
rm -rf ./build/*
cp web/html/index.html ./build/
cp -r web/favicon/ ./build/
cp -r web/static/ ./build/
mkdir ./build/pkg/
cp -r ./pkg/jelatofish.js ./pkg/jelatofish_bg.wasm ./build/pkg/
'''
]
dependencies = ["wasm"]

[tasks.wasm]
description = "web向けのwasmにコンパイルする"
command = "wasm-pack"
args = ["build", "--target", "web"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.release]
command = "cargo"
args = ["build", "--release"]
dependencies = ["clean"]

[tasks.run]
command = "cargo"
args = ["run"]
